ready for check then release
EuroLinux/eurolinux-open-docs pull request #19
Opened 2021-11-25 13:18 UTC by AlexBaranowski

2021-11-25 14:29 UTC, tompods requested changes
Nice one! Let's just fix some minor errors.

2021-11-25 14:29 UTC, tompods commented on docs/release-notes/8.5.md
> +- OpenSCAP framework - added new profiles and multiple changes and enhancement
enhancement**s**?

2021-11-25 14:29 UTC, tompods commented on docs/release-notes/8.5.md
> +Later versions of the following components are now available:
How about _New versions_?

2021-11-25 14:29 UTC, tompods commented on docs/release-notes/8.5.md
> +Among the others, the following packages were updated and enhancement:
"and enhancement"?
Maybe _and enhanced_ if we're talking about the quality improvements these updates bring.

2021-11-25 14:29 UTC, tompods commented on docs/release-notes/8.5.md
> +Batteries repository contains packages that are needed to rebuild distribution
_the distribution_ - we're talking about EuroLinux exclusively

2021-11-25 14:29 UTC, tompods commented on docs/release-notes/8.5.md
> +Gaia build system was updated in all interested parties environments. We also
_parties'_

2021-11-25 14:29 UTC, tompods commented on docs/release-notes/8.5.md
> +changed the rebuild policy. Non of our customers were interested in using RHEL
_None_

2021-11-25 14:29 UTC, tompods commented on docs/release-notes/8.5.md
> +- EuroLinux reverted changes that made DockerHub default container image
_the changes_, _the default_?

2021-11-25 22:21 UTC, AlexBaranowski commented
@tompods fixed 😄

2021-11-26 08:17 UTC, tompods approved these changes

2021-11-26 08:17 UTC, merged