add caps and limits information
EuroLinux/eurolinux-open-docs pull request #33
Opened 2022-02-17 11:06 UTC by AlexBaranowski

@tompods it should be short one.

Based mostly on the https://access.redhat.com/articles/rhel-limits

2022-02-17 12:10 UTC, tompods requested changes

2022-02-17 12:10 UTC, tompods commented on docs/knowledge-base/eurolinux-capabilities-and-limits.md
> +The minimum requirements are in place because it might not be possible to
"are in place" -> "have been provided below"

2022-02-18 14:27 UTC, AlexBaranowski commented on docs/knowledge-base/eurolinux-capabilities-and-limits.md
> +Availability add-ons that are freely available with subscription or free
RHEL and OL require additional subscriptions for HA and RS. When clients buy our products, we support HA and RS without additional cost. That's why I wrote freely available with a subscription. Also, it's part of the "true product" core company value.

2022-02-18 14:28 UTC, AlexBaranowski commented
@tompods please review. You are the 🥇

2022-02-18 15:26 UTC, tompods commented
Almost OK, just use the exact expression: "for the systems **for** which support is" (the "for" word in bold is missing)

2022-02-18 16:32 UTC, AlexBaranowski commented
@tompods you can merge

2022-02-18 17:17 UTC, tompods approved these changes

2022-02-18 17:17 UTC, merged